# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('goodsName', models.CharField(max_length=50)),
                ('count', models.CharField(max_length=10)),
                ('createTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-createTime',),
            },
        ),
    ]
