# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_goods_ordergoods_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='remark',
        ),
        migrations.AddField(
            model_name='orders',
            name='content',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orders',
            name='open_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='orders',
            name='client_name',
            field=models.CharField(max_length=30),
        ),
    ]
