# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_auto_20170918_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='audioId',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='orders',
            name='open_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
